# Generated by Django 4.2.4 on 2023-09-13 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("task_manager", "0005_team_tasks_alter_team_teammates"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="team",
            name="tasks",
        ),
        migrations.AddField(
            model_name="task",
            name="team",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to="task_manager.team",
            ),
            preserve_default=False,
        ),
    ]
