# Generated by Django 4.2.4 on 2023-09-13 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0006_remove_team_tasks_task_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='team',
        ),
    ]
